import type { Metadata } from 'next'
import { Inter, Agbalumo } from 'next/font/google'
import styles from './page.module.css';
import './globals.css'

const agbalumo = Agbalumo({ subsets:[], weight: ['400']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={agbalumo.className}>
      <main className={styles.main}>
        <div className={styles.header}>
          <h1>Taryn Martin</h1>
        </div>
        <div className={styles.mainContent}>
          <div className={styles.headshotContainer}>
            <div className={styles.headshot} />
          </div>
          <div className={styles.content}>
            {children}
          </div>
        </div>
      </main>
      </body>
    </html>
  )
}
